### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by Baural** [plutov/packagemain#15]
FROM golang

RUN mkdir -p /go/src/12-GO-KIT-1
Hi, I added a workdir in each service. However docker-compose up still worikng not correct. 

Do you know some solutions?

====================================================

ADD . /go/src/12-GO-KIT-1
WORKDIR /go/src/12-GO-KIT-1/bugs

RUN go get  -t -v ./...
RUN go get  github.com/canthefason/go-watcher
RUN go install github.com/canthefason/go-watcher/cmd/watcher

ENTRYPOINT  watcher -run 12-GO-KIT-1/bugs/cmd  -watch 12-GO-KIT-1/bugs

====================================================
Step 1/8 : FROM golang
 ---> 315fc470b445
Step 2/8 : RUN mkdir -p /go/src/12-GO-KIT-1
 ---> Using cache
 ---> b3601e10281c
Step 3/8 : ADD . /go/src/12-GO-KIT-1
 ---> 44a1e7083947
Step 4/8 : WORKDIR /go/src/12-GO-KIT-1/notificator
 ---> Running in e379c3b63bfa
Removing intermediate container e379c3b63bfa
 ---> 604409109128
Step 5/8 : RUN go get  -t -v ./...
 ---> Running in eff882c0f930
github.com/go-kit/kit (download)
github.com/go-logfmt/logfmt (download)
github.com/golang/protobuf (download)
get "google.golang.org/protobuf/encoding/prototext": found meta tag get.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at //google.golang.org/protobuf/encoding/prototext?go-get=1
get "google.golang.org/protobuf/encoding/prototext": verifying non-authoritative meta tag
google.golang.org/protobuf (download)

**Comment by plutov** [comment]
Some dependencies have changed, this project needs refactoring to use go modules instead.

**Comment by plutov** [comment]
@Baural this code was very old and dependencies have changed. So I added go modules and fixed this. Please try again.
