### ISSUE TITLE
16-wails-desktop-app gauge is not getting data

### ISSUE THREAD

**Issue by enverromon** [plutov/packagemain#16]
Hi :)
The gauge is not getting any event from Go code.

On 16-wails-desktop-app/cpustats/frontend/src/components/CPUUsage.vue 
`wails.events.on("cpu_usage", cpu_usage => {`
must be 
`window.wails.events.on("cpu_usage", cpu_usage => {`

Regards

**Comment by enverromon** [comment]
Sorry, my mistake :(

**Comment by enverromon** [comment]
Ok, the problem wasn't where I thought.
The correct fix is 
`wails.Events.On`
instead of
`wails.events.on`

**Comment by plutov** [comment]
@enverromon can you please create a PR for this fix?

**Comment by enverromon** [comment]
You got it :)

**Comment by plutov** [comment]
Thank you a lot! I tested with new Wails version and it worked well.
