### ISSUE TITLE
Please look into reducing plagerism

### ISSUE THREAD

**Issue by PaluMacil** [plutov/packagemain#2]
The author [Jacob Martins' post on Oauth2](https://jacobmartins.com/2016/02/29/getting-started-with-oauth2-in-go/) mentioned on Reddit that your oauth2 post is a copy-paste of his blog without credit. The author was pretty gracious, saying that he feels sad to not be credited, but that he sees you too want to help people learn. That's pretty generous considering he'd be justified feeling much angrier. I recommend crediting the author of material you use here. If you take material that isn't licensed for reuse, you could eventually wind up with legal trouble.

**Comment by plutov** [comment]
Agree, I was thinking how to solve it. So I added a link to the video description - https://www.youtube.com/watch?v=OdyXIi6DGYw
