### ISSUE TITLE
facing the issue at go mod download in docker file

### ISSUE THREAD

**Issue by nilerajput91** [plutov/packagemain#22]
---> Running in 6fd0a18dac6a
golang.org/x/exp@v0.0.0-20190121172915-509febef88a4: stream error: stream ID 159; INTERNAL_ERROR
golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd: stream error: stream ID 163; INTERNAL_ERROR
golang.org/x/text@v0.3.0: stream error: stream ID 173; INTERNAL_ERROR
golang.org/x/tools@v0.0.0-20190524140312-2c0ae7006135: stream error: stream ID 167; INTERNAL_ERROR
The command '/bin/sh -c go mod download' returned a non-zero code: 1

**Comment by leopedroso45** [comment]
$GOPATH/go.mod exists but should not
ERROR: Service 'app' failed to build: The command '/bin/sh -c go mod download' returned a non-zero code: 1

How did you solve that?

**Comment by plutov** [comment]
@nilerajput91 @leopedroso45 from which video/folder is that?
