### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by leobewater** [plutov/packagemain#35]
Hi Alex.

When I run this command to generate the grpc for notificator, it's showing the exit error. But most of the files seem to be generated.

> kit generate service notificator -t grpc --dmw
ERRO[0000] exit status 1                                

When I run 
> docker-compose up

It's returning this error. I can't figure it out. Please help. Much appreciated!

go: go.mod file not found in current directory or any parent directory; see 'go help modules'
ERROR: Service 'bugs' failed to build : The command '/bin/sh -c go get  -t -v ./...' returned a non-zero code: 1

**Comment by plutov** [comment]
Can you check again please? it works when I build it manually:
```
cd ./bugs
CGO_ENABLED=0 GOOS=linux go build -mod vendor -o server ./cmd/main.go
```
