### ISSUE TITLE
Prediction not correct

### ISSUE THREAD

**Issue by AhmedX6** [plutov/packagemain#4]
Hello,

I'm facing issues with the predictions. I'm using this python program to train my dataset [retrain.py](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py
) and from this program [label_image.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/label_image.py) I have good predictions

What's the difference between this program and the go program ? What's the adaptation I should do to make it work as label_image.py ?

Thanks for help

**Comment by plutov** [comment]
Hi @AhmedX6 the label_image.py is very similar to https://github.com/plutov/packagemain/blob/master/04-tensorflow-image-recognition/main.go, it uses inception model so the graph is the same.
