### ISSUE TITLE
Google Home

### ISSUE THREAD

**Issue by Dontmindmes** [plutov/packagemain#5]
Can you make another video about making actions for Google Home and maybe make it so it grabs bitcoin price from coinmarketcap.com

and have it grab what the user asks for like
Whats the price of ETH

**Comment by plutov** [comment]
Hi, yes it is very interesting example!

Maybe I can try with new DialogFlow Go package - https://godoc.org/google.golang.org/api/dialogflow/v2beta1

**Comment by Dontmindmes** [comment]
Yes thank you! I and other would love to watch a video on it

**Comment by plutov** [comment]
Hi @Dontmindmes I tried to do this and almost finished when I realized that the content of the video / post would be absolutely the same as I had before, so I am closing this ticket for now. Sorry about this.
